apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: 80
      targetPort: {{ .containerPort }}
  {{- end }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}